name: Automated dev builds

on:
  workflow_dispatch:
  push:
jobs:
  fabric:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Fabric
        run: ./gradlew -p fabric build


      - name: Publish FABRIC artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'fabric/build/libs/*'
          username: FABRIC builds
          avatar: 'https://avatars.githubusercontent.com/u/21025855?s=280&v=4'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%
  forge:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build Forge
        run: ./gradlew -p forge build


      - name: Publish FORGE artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'forge/build/libs/*'
          username: FORGE builds
          avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTANykFWjQtnuOz92gYuvGaePcC2e-4mTsifrwIUCrO__V8v4wOvBx_kpDW8geKPAejm8k&usqp=CAU'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%
  neoforge:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Data Generation
        run: ./gradlew -p forge Data
        continue-on-error: true

      - name: Build NeoForge
        run: ./gradlew -p neoforge build


      - name: Publish NEOFORGE artifacts
        uses: DrTheodor/discord-webhook-upload-action@v1.2
        with:
          url: ${{ secrets.DEV_BUILDS }}
          file: 'neoforge/build/libs/*'
          username: NEOFORGE builds
          avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGXA4X8mmDNJHpXHgU_ndkcOz8kqU10qp2EA&s'
          commit: '> :sparkles: [%MESSAGE%](<%LINK%>) by [%AUTHOR%](<%AUTHOR_LINK%>)'
          message: |
            <:new1:1253371736510959636><:new2:1253371805734015006> New `${{ github.repository }}` dev build `#${{ github.run_number }}`:
            %COMMITS%